[project]
name = "streamdcbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.13",
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "PyNaCl>=1.5.0",
    "yt-dlp>=2024.1.0",
]
